services:
  agent:
    build: ./agent
    ports:
      - "4000:4000"
    env_file:
      - ./agent/.env

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - agent
