version: '3.8'
services:
  multi-agent:
    build: ./agent
    ports:
      - "4000:4000"
    depends_on:
      - audit
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - agent

  audit:
    build: ./audit
    volumes:
      - ./target-project:/app
    environment:
      - NODE_ENV=production
