version: '3.8'
services:
  multi-agent:
    build: ./agent
    ports:
      - "4000:4000"
    depends_on:
      - audit
    environment:
      - TAVILY_API_KEY=your_tavily_api_key
      - GITHUB_TOKEN=your_github_token # TODO: Add this to the .env file for GitHub advisory research

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - agent

  audit:
    build: ./audit
    volumes:
      - ./target-project:/app
    environment:
      - NODE_ENV=production
